CREATE DATABASE Customer_behavior;
use customer_behavior;
show tables;
DESCRIBE customer_shopping_behavior;

-- Some Questions:
-- Q1. What is the total revenue generated by male vs female customers?
SELECT Gender, SUM(`Purchase Amount (USD)`) as revenue FROM customer_shopping_behavior GROUP BY Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT `Customer ID`, `Purchase Amount (USD)` FROM customer_shopping_behavior WHERE `Discount Applied` = 'Yes' AND `Purchase Amount (USD)` 
>= (SELECT AVG(`Purchase Amount (USD)`) FROM customer_shopping_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased`, ROUND(AVG(`Review Rating`),2) as `Average Product Rating` FROM customer_shopping_behavior GROUP BY `Item Purchased`
ORDER BY AVG(`Review Rating`) DESC LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping?
SELECT `Shipping Type`, ROUND(AVG(`Purchase Amount (USD)`),2) FROM customer_shopping_behavior  
WHERE `Shipping Type` IN ('Standard' , 'Express') GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more ? Compare average spend and total revenue between subscribers and non- subscribers
SELECT `Subscription Status` , COUNT(`Customer ID`) AS `Total Customers`, ROUND(AVG(`Purchase Amount (USD)`),2) AS Avg_Spend, 
ROUND(SUM(`Purchase Amount (USD)`), 2) AS Total_Revenue FROM customer_shopping_behavior GROUP BY `Subscription Status` ORDER BY Total_Revenue, Avg_Spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased`, ROUND(SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END ) / COUNT(*) *100, 2) AS `Discount_rate`
FROM customer_shopping_behavior GROUP BY `Item Purchased` ORDER BY `Discount_rate` DESC LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?
WITH Customer_Type AS (
    SELECT
        `Customer ID`,
        `Previous Purchases`,
        CASE
            WHEN `Previous Purchases` = 1 THEN 'New'
            WHEN `Previous Purchases` BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_segment
    FROM customer_shopping_behavior
)

SELECT
    Customer_segment,
    COUNT(*) AS `No of Customers`
FROM Customer_Type
GROUP BY Customer_segment;
-- Q8. What are the top 3 most purchased products within each category?
WITH `Item_counts` AS (
SELECT Category, `Item Purchased`, COUNT(`Customer ID`) AS `Total_orders`, 
ROW_NUMBER() OVER (PARTITION BY Category ORDER BY COUNT(`Customer ID`) DESC) AS `Item_rank` 
FROM customer_shopping_behavior GROUP BY Category, `Item Purchased`)
SELECT `Item_rank`, Category, `Item Purchased`, `Total_orders` FROM Item_counts 
WHERE `Item_rank` <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT `Subscription Status` , COUNT(`Customer ID`) AS `Repeat_buyers` 
FROM customer_shopping_behavior WHERE `Previous Purchases` >5 GROUP BY `Subscription Status`;

-- Q10. What is the revenue contribution of each age roup?
SELECT Age_group, 
SUM(`Purchase Amount (usd)`) AS Total_revenue FROM customer_shopping_behavior 
GROUP BY Age_group ORDER BY Total_revenue DESC;